CREATE TYPE DOMAIN_VISIBILITY_TYPE AS ENUM ('public', 'restricted', 'private');
CREATE TYPE DOMAIN_MEMBERSHIP_ACCEPTANCE AS ENUM ('open', 'invite-only', 'confirmation');
CREATE TYPE DOMAIN_MEMBERSHIP_ROLE AS ENUM ('member', 'moderator', 'admin','creator');
CREATE TYPE DOMAIN_STATUS AS ENUM ('active', 'banned', 'expired', 'suspended');

DROP TABLE IF EXISTS domains;
CREATE TABLE IF NOT EXISTS domains(
    domain_name VARCHAR(50) UNIQUE NOT NULL,
    domain_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    domain_visibility DOMAIN_VISIBILITY_TYPE NOT NULL,
    membership_acceptance DOMAIN_MEMBERSHIP_ACCEPTANCE NOT NULL,
    domain_status DOMAIN_STATUS NOT NULL
);

DROP TABLE IF EXISTS posts;
CREATE TABLE IF NOT EXISTS posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    body TEXT,
    author VARCHAR(60),
    title VARCHAR(255),
    domain_id INT NOT NULL,
    FOREIGN KEY (domain_id) REFERENCES domains(domain_id)
);

DROP TABLE IF EXISTS domains_membership;
CREATE TABLE IF NOT EXISTS domains_membership(
    member_id VARCHAR(155) NOT NULL,
    domain_id INT NOT NULL,
    member_role DOMAIN_MEMBERSHIP_ROLE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    membership_status DOMAIN_STATUS NOT NULL,
    membership_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

DROP TABLE IF EXISTS action_logs;
CREATE TABLE IF NOT EXISTS action_logs(
    table_name VARCHAR(75) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    document_id bigint NOT NULL,
    logs_message TEXT NOT NULL,
    user_id VARCHAR(155) NOT NULL,
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);