DROP TABLE IF EXISTS posts;
CREATE TABLE IF NOT EXISTS POSTS(
    post_id bigint GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    body TEXT,
    author VARCHAR(60),
    title VARCHAR(255)
);

CREATE TYPE DOMAIN_VISIBILITY_TYPE ENUM('public', 'restricted', 'private');

DROP TABLE IF EXISTS domain;
CREATE TABLE IF NOT EXISTS domain(
    domain_name VARCHAR(50) UNIQUE NOT NULL,
    domain_id INT GENERATED ALWAYS AS IDENTITY,
    description text,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    domain_visibility DOMAIN_VISIBILITY_TYPE NOT NULL
)