DROP TABLE IF EXISTS POSTS;
CREATE TABLE IF NOT EXISTS POSTS(
    post_id bigint GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    body TEXT,
    author VARCHAR(60),
    title VARCHAR(255)
);