import type { Metadata } from "next";
import { SidebarLayout } from "@/components/sidebar-layout/SidebarLayout";
import React from "react";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <SignedIn>
            <SidebarLayout>{children}</SidebarLayout>
          </SignedIn>
          <SignedOut>{children}</SignedOut>
        </ClerkProvider>
      </body>
    </html>
  );
}
